<a href="https://colab.research.google.com/github/analystkritii/MACHINE-LEARNING--DATA-HANDLING/blob/main/handling_missing_value_IN_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
#created the dataset
#data collection
df_retail = pd.DataFrame({
'Customer_ID': [1,2,3,4,5,6],
'Age': [25,30,28,32,29,31],
'Annual_Spend': [50000, np.nan, 48000, np.nan, 51000, 49500]
})
df_retail

   Customer_ID  Age  Annual_Spend
0            1   25       50000.0
1            2   30           NaN
2            3   28       48000.0
3            4   32           NaN
4            5   29       51000.0
5            6   31       49500.0

In [2]:
df_retail.isnull().sum()

Customer_ID     0
Age             0
Annual_Spend    2
dtype: int64

In [3]:
len(df_retail)

6

In [4]:
(df_retail.isnull().sum()/len(df_retail))*100

Customer_ID      0.000000
Age              0.000000
Annual_Spend    33.333333
dtype: float64

In [5]:
df_retail['Annual_Spend'].skew()

np.float64(-0.5599999999999999)

In [6]:
df_retail['Annual_Spend']=df_retail['Annual_Spend'].fillna(
df_retail['Annual_Spend'].mean(),
inplace=True
)

/tmp/ipykernel_4196/2769441584.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_retail['Annual_Spend']=df_retail['Annual_Spend'].fillna(

In [7]:
df_retail

   Customer_ID  Age Annual_Spend
0            1   25         None
1            2   30         None
2            3   28         None
3            4   32         None
4            5   29         None
5            6   31         None

In [8]:
df_salary = pd.DataFrame({
'Employee': ['A','B','C','D','E','F'],
'Salary': [30000, 35000, 40000, 500000, 42000, np.nan]
})
df_salary

  Employee    Salary
0        A   30000.0
1        B   35000.0
2        C   40000.0
3        D  500000.0
4        E   42000.0
5        F       NaN

In [9]:
(df_salary.isnull().sum()/len(df_salary))*100

Employee     0.000000
Salary      16.666667
dtype: float64

In [10]:
df_salary['Salary'].skew()

np.float64(2.233238926058897)

In [11]:
df_salary['Salary'].fillna(
df_salary['Salary'].median(),
inplace=True
)

/tmp/ipykernel_4196/1640292219.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_salary['Salary'].fillna(

In [12]:
df_salary

  Employee    Salary
0        A   30000.0
1        B   35000.0
2        C   40000.0
3        D  500000.0
4        E   42000.0
5        F   40000.0

In [13]:
df_customer = pd.DataFrame({
'Customer_ID': [1,2,3,4,5,6],
'City': ['Mumbai','Delhi',np.nan,'Mumbai',np.nan,'Delhi']
})
df_customer

   Customer_ID    City
0            1  Mumbai
1            2   Delhi
2            3     NaN
3            4  Mumbai
4            5     NaN
5            6   Delhi

In [14]:
(df_customer.isnull().sum()/len(df_customer))*100

Customer_ID     0.000000
City           33.333333
dtype: float64

In [15]:
df_customer['City'].fillna(
df_customer['City'].mode()[0],
inplace=True
)

/tmp/ipykernel_4196/3002770696.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_customer['City'].fillna(

In [16]:
df_customer

   Customer_ID    City
0            1  Mumbai
1            2   Delhi
2            3   Delhi
3            4  Mumbai
4            5   Delhi
5            6   Delhi

In [17]:
df_customer['City'].fillna("Unknown", inplace=True)

/tmp/ipykernel_4196/189649353.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_customer['City'].fillna("Unknown", inplace=True)

In [18]:
df_customer

   Customer_ID    City
0            1  Mumbai
1            2   Delhi
2            3   Delhi
3            4  Mumbai
4            5   Delhi
5            6   Delhi